FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster-arm32v7 AS build-env
WORKDIR /app


COPY . ./
RUN dotnet restore source/IotEdgePerf.Transmitter.Edge/*.csproj
RUN dotnet publish source/IotEdgePerf.Transmitter.Edge/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "Transmitter.Edge.dll"]