FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore source/IotEdgePerf.Transmitter.Edge/*.csproj
RUN dotnet publish source/IotEdgePerf.Transmitter.Edge/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/out ./

USER root
RUN mkdir /usr/local/cache
RUN chmod 777 /usr/local/cache

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "Transmitter.Edge.dll"]