name: Docker Image CI

on:
  push:
    branches: [ main, automated_image_creation ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # set environment variables for actions from file
    - name: Set Variable
      uses: deep-mm/set-variables@v1.0
      with:
        variableFileName: 'action_variables'


    # push image to registry only if build on GitHub and not a pull_request
    - name: "Set push from Context"
      env:
        PUSH_VAR: ${{ github.event_name != 'pull_request' && !env.ACT }}
      run: |
        if ${PUSH_VAR} == true; then
          echo "::set-env name=push::true"
          echo "push set to true"
        else
          echo "::set-env name=push::false"
          echo "push set to false"
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Login
      if: env.push
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ env.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.GHCRPAT }}
        logout: true

    - name: Build and push Docker image "sink"
      uses: docker/build-push-action@v2
      with:
        context: ./modules/sink/
        file: ./modules/sink/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ env.push }}
        tags: |
          ${{ env.CONTAINER_REGISTRY_PATH }}/sink:${{ github.run_number }}
          ${{ env.CONTAINER_REGISTRY_PATH }}/sink:latest
        labels: org.opencontainers.image.source https://github.com/arlotito/edge-simulation-framework

    - name: Build and push Docker image "source"
      uses: docker/build-push-action@v2
      with:
        context: ./modules/source/
        file: ./modules/source/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: ${{ env.push }}
        tags: |
          ${{ env.CONTAINER_REGISTRY_PATH }}/source:${{ github.run_number }}
          ${{ env.CONTAINER_REGISTRY_PATH }}/source:latest
        labels: org.opencontainers.image.source https://github.com/arlotito/edge-simulation-framework